import { useMemo, useState } from "react";
import { ArrowBackRounded, ArrowForwardRounded, CheckCircleRounded, ContentCopyRounded, OpenInNewRounded, SendRounded } from "@mui/icons-material";
import "./Pesquisa.css";

const initial={estabelecimento:"",responsavel:"",cidade:"",estado:"",whatsapp:"",email:"",tipo:"",colaboradores:"",animaisDia:"",ferramentas:[],checkin:"",vacinas:"",medicamentos:"",comunicacao:"",maiorDor:"",investimento:"",interesse:"",beta:"",contato:""};
const PUBLIC_URL=`${window.location.origin}/pesquisa-publica`;
const steps=["Perfil","Operação","Dores","Interesse"];
export default function Pesquisa({publicMode=false}){
 const [form,setForm]=useState(initial),[step,setStep]=useState(0),[sent,setSent]=useState(false),[copied,setCopied]=useState(false),[error,setError]=useState("");
 const responses=useMemo(()=>JSON.parse(localStorage.getItem("pethaven_pesquisa_respostas")||"[]"),[sent]);
 const change=e=>setForm(v=>({...v,[e.target.name]:e.target.value}));
 const toggle=value=>setForm(v=>({...v,ferramentas:v.ferramentas.includes(value)?v.ferramentas.filter(x=>x!==value):[...v.ferramentas,value]}));
 const requiredByStep=[["estabelecimento","responsavel","cidade","estado","whatsapp","tipo"],["colaboradores","animaisDia","checkin","vacinas","medicamentos","comunicacao"],["maiorDor","investimento"],["interesse","beta","contato"]];
 function next(){const missing=requiredByStep[step].some(k=>!form[k]||(Array.isArray(form[k])&&!form[k].length));if(missing){setError("Preencha todos os campos obrigatórios desta etapa.");return}setError("");setStep(s=>Math.min(s+1,3));window.scrollTo({top:0,behavior:"smooth"})}
 function submit(e){e.preventDefault();const missing=requiredByStep[3].some(k=>!form[k]);if(missing){setError("Preencha todos os campos obrigatórios desta etapa.");return}const prev=JSON.parse(localStorage.getItem("pethaven_pesquisa_respostas")||"[]");localStorage.setItem("pethaven_pesquisa_respostas",JSON.stringify([...prev,{...form,id:Date.now(),enviadoEm:new Date().toISOString()}]));setSent(true);window.scrollTo({top:0,behavior:"smooth"})}
 async function copy(){await navigator.clipboard.writeText(PUBLIC_URL);setCopied(true);setTimeout(()=>setCopied(false),1600)}
 if(sent)return <div className={`research-page ${publicMode?"research-page--public":""}`}><div className="research-success"><CheckCircleRounded/><h1>Resposta recebida. Obrigado!</h1><p>Sua experiência ajudará a definir as prioridades do PetHaven.</p><button onClick={()=>{setForm(initial);setStep(0);setSent(false)}}>Enviar outra resposta</button></div></div>;
 return <div className={`research-page ${publicMode?"research-page--public":""}`}>
  <section className="research-hero"><span>1º Diagnóstico Nacional • PetHaven</span><h1>Gestão de Hotéis e Creches Pet</h1><p>Uma pesquisa prática para entender a rotina dos estabelecimentos e construir uma solução realmente útil.</p>{!publicMode&&<div className="research-admin"><div><strong>{responses.length}</strong><small>respostas salvas neste navegador</small></div><button onClick={copy}><ContentCopyRounded/>{copied?"Copiado":"Copiar link"}</button><a href={PUBLIC_URL} target="_blank" rel="noreferrer"><OpenInNewRounded/>Abrir pesquisa pública</a></div>}</section>
  <section className="research-shell"><div className="research-progress"><div className="research-progress__top"><strong>Etapa {step+1} de {steps.length}</strong><span>{steps[step]}</span></div><div className="research-progress__bar"><span style={{width:`${((step+1)/steps.length)*100}%`}}/></div><div className="research-progress__labels">{steps.map((x,i)=><span className={i<=step?"active":""} key={x}>{i+1}. {x}</span>)}</div></div>
  <form onSubmit={submit}>
   {step===0&&<div className="survey-card"><h2>Perfil do estabelecimento</h2><p>Conte-nos quem você é e onde atua.</p><div className="survey-grid"><label>Nome do estabelecimento *<input name="estabelecimento" value={form.estabelecimento} onChange={change}/></label><label>Responsável *<input name="responsavel" value={form.responsavel} onChange={change}/></label><label>Cidade *<input name="cidade" value={form.cidade} onChange={change}/></label><label>Estado *<input name="estado" maxLength="2" value={form.estado} onChange={change} placeholder="PR"/></label><label>WhatsApp *<input name="whatsapp" value={form.whatsapp} onChange={change}/></label><label>E-mail<input type="email" name="email" value={form.email} onChange={change}/></label><label className="full">Tipo de negócio *<select name="tipo" value={form.tipo} onChange={change}><option value="">Selecione</option><option>Hotel pet</option><option>Creche pet</option><option>Hotel + Creche</option><option>Pet shop / clínica</option><option>Outro</option></select></label></div></div>}
   {step===1&&<div className="survey-card"><h2>Como funciona hoje?</h2><p>Ajude-nos a entender sua operação.</p><div className="survey-grid"><label>Quantidade de colaboradores *<select name="colaboradores" value={form.colaboradores} onChange={change}><option value="">Selecione</option><option>1 a 3</option><option>4 a 10</option><option>11 a 20</option><option>Mais de 20</option></select></label><label>Animais atendidos por dia *<select name="animaisDia" value={form.animaisDia} onChange={change}><option value="">Selecione</option><option>Até 10</option><option>11 a 30</option><option>31 a 60</option><option>Mais de 60</option></select></label><label>Tempo médio de check-in *<select name="checkin" value={form.checkin} onChange={change}><option value="">Selecione</option><option>Até 5 minutos</option><option>5 a 10 minutos</option><option>10 a 20 minutos</option><option>Mais de 20 minutos</option></select></label><label>Controle de vacinas *<select name="vacinas" value={form.vacinas} onChange={change}><option value="">Selecione</option><option>Manual</option><option>Planilha</option><option>Sistema</option><option>Não controlamos</option></select></label><label>Controle de medicamentos *<select name="medicamentos" value={form.medicamentos} onChange={change}><option value="">Selecione</option><option>Papel</option><option>WhatsApp</option><option>Planilha</option><option>Sistema</option></select></label><label>Comunicação com tutores *<select name="comunicacao" value={form.comunicacao} onChange={change}><option value="">Selecione</option><option>WhatsApp</option><option>Telefone</option><option>Aplicativo</option><option>Outro</option></select></label></div><h3>Ferramentas utilizadas</h3><div className="choice-grid">{["WhatsApp","Papel","Excel","Google Forms","Sistema próprio","Software de terceiros"].map(x=><button type="button" onClick={()=>toggle(x)} className={form.ferramentas.includes(x)?"choice active":"choice"} key={x}>{form.ferramentas.includes(x)&&<CheckCircleRounded/>}{x}</button>)}</div></div>}
   {step===2&&<div className="survey-card"><h2>Dores e prioridades</h2><p>Este bloco orientará diretamente o desenvolvimento do PetHaven.</p><label>Se pudesse eliminar apenas um problema operacional hoje, qual seria? *<textarea rows="6" name="maiorDor" value={form.maiorDor} onChange={change}/></label><label>Quanto investiria por mês em uma solução que resolvesse essas dores? *<select name="investimento" value={form.investimento} onChange={change}><option value="">Selecione</option><option>Não pagaria no momento</option><option>Até R$ 50</option><option>R$ 51 a R$ 100</option><option>R$ 101 a R$ 200</option><option>Acima de R$ 200</option></select></label></div>}
   {step===3&&<div className="survey-card"><h2>Interesse no PetHaven</h2><p>Última etapa: diga como deseja participar.</p><div className="survey-grid"><label>Tem interesse na solução? *<select name="interesse" value={form.interesse} onChange={change}><option value="">Selecione</option><option>Sim</option><option>Talvez</option><option>Não</option></select></label><label>Aceitaria testar gratuitamente? *<select name="beta" value={form.beta} onChange={change}><option value="">Selecione</option><option>Sim</option><option>Talvez</option><option>Não</option></select></label><label className="full">Podemos entrar em contato? *<select name="contato" value={form.contato} onChange={change}><option value="">Selecione</option><option>Sim</option><option>Não</option></select></label></div></div>}
   {error&&<div className="survey-error">{error}</div>}<div className="survey-actions">{step>0&&<button type="button" className="back" onClick={()=>{setError("");setStep(s=>s-1)}}><ArrowBackRounded/>Voltar</button>}<span/>{step<3?<button type="button" className="next" onClick={next}>Próxima etapa<ArrowForwardRounded/></button>:<button className="next" type="submit"><SendRounded/>Enviar participação</button>}</div>
  </form></section>
 </div>
}
